version: "3.9"

networks:
  game_stat_network:
    driver: bridge

volumes:
  shared-logs:
    driver: local
    driver_opts:
      type: "tmpfs"
      device: "tmpfs"
      o: "size=256m,uid=1000"

services:
  auth1:
    container_name: pad_auth_1
    hostname: pad_auth_1
    build: ./auth
    environment:
      SERVICE_PORT: "8000"
      CACHE: "pad_cache"
      DISCOVERY: "pad_discovery"
      SERVICE_NAME: "pad_auth_1"
      FLASK_DEBUG: "False"
    depends_on:
      - discovery
      - cache
    networks:
      - game_stat_network
    volumes:
      - shared-logs:/logs

  auth2:
    container_name: pad_auth_2
    hostname: pad_auth_2
    build: ./auth
    environment:
      SERVICE_PORT: "8000"
      CACHE: "pad_cache"
      DISCOVERY: "pad_discovery"
      SERVICE_NAME: "pad_auth_2"
      FLASK_DEBUG: "False"
    depends_on:
      - discovery
      - cache
    networks:
      - game_stat_network
    volumes:
      - shared-logs:/logs

  auth3:
    container_name: pad_auth_3
    hostname: pad_auth_3
    build: ./auth
    environment:
      SERVICE_PORT: "8000"
      CACHE: "pad_cache"
      DISCOVERY: "pad_discovery"
      SERVICE_NAME: "pad_auth_3"
      FLASK_DEBUG: "False"
    depends_on:
      - discovery
      - cache
    networks:
      - game_stat_network
    volumes:
      - shared-logs:/logs

  cache:
    container_name: pad_cache
    hostname: pad_cache
    build: ./cache
    environment:
      REDIS_HOST: "pad_redis"
    depends_on:
      - redis
    networks:
      - game_stat_network
    volumes:
      - shared-logs:/logs

  discovery:
    container_name: pad_discovery
    hostname: pad_discovery
    build: ./discovery/Discovery/Discovery
    environment:
      FLASK_DEBUG: "False"
    networks:
      - game_stat_network
    volumes:
      - shared-logs:/logs

  game_stat1:
    container_name: pad_game_stat_1
    hostname: pad_game_stat_1
    build: ./game_stat
    environment:
      SERVICE_PORT: "8003"
      POSTGRES: "pad_postgres"
      CACHE: "pad_cache"
      DISCOVERY: "pad_discovery"
      SERVICE_NAME: "pad_game_stat_1"
      FLASK_DEBUG: "False"
    depends_on:
      discovery: 
        condition: service_started
      cache: 
        condition: service_started
      postgres: 
        condition: service_healthy
    networks:
      - game_stat_network
    volumes:
      - shared-logs:/logs

  game_stat2:
    container_name: pad_game_stat_2
    hostname: pad_game_stat_2
    build: ./game_stat
    environment:
      SERVICE_PORT: "8003"
      POSTGRES: "pad_postgres"
      CACHE: "pad_cache"
      DISCOVERY: "pad_discovery"
      SERVICE_NAME: "pad_game_stat_2"
      FLASK_DEBUG: "False"
    depends_on:
      discovery: 
        condition: service_started
      cache: 
        condition: service_started
      postgres: 
        condition: service_healthy
    networks:
      - game_stat_network
    volumes:
      - shared-logs:/logs

  game_stat3:
    container_name: pad_game_stat_3
    hostname: pad_game_stat_3
    build: ./game_stat
    environment:
      SERVICE_PORT: "8003"
      POSTGRES: "pad_postgres"
      CACHE: "pad_cache"
      DISCOVERY: "pad_discovery"
      SERVICE_NAME: "pad_game_stat_3"
      FLASK_DEBUG: "False"
    depends_on:
      discovery: 
        condition: service_started
      cache: 
        condition: service_started
      postgres: 
        condition: service_healthy
    networks:
      - game_stat_network
    volumes:
      - shared-logs:/logs

  gateway:
    container_name: pad_gateway
    hostname: pad_gateway
    build: ./gateway
    ports:
      - "8004:8004"
    environment:
      DISCOVERY: "pad_discovery"
      FLASK_DEBUG: "False"
    depends_on:
      - discovery
      - game_stat1
      - game_stat2
      - game_stat3
      - auth1
      - auth2
      - auth3
    networks:
      - game_stat_network
    volumes:
      - shared-logs:/logs

  postgres:
    container_name: pad_postgres
    hostname: pad_postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: game_stat
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    networks:
      - game_stat_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: pad_redis
    hostname: pad_redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - game_stat_network
    restart: unless-stopped

  elk:
    container_name: pad_elk
    hostname: pad_elk
    image: sebp/elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    environment:
      ELASTICSEARCH_START: 1
      LOGSTASH_START: 1
      KIBANA_START: 1
    networks:
      - game_stat_network
    volumes:
      - shared-logs:/logs
      - ${PWD}/elk/01-logs-filter.conf:/etc/logstash/conf.d/01-logs-filter.conf