"""empty message

Revision ID: 383cc4b3e329
Revises: 557d591a3831
Create Date: 2022-09-27 22:15:51.085656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '383cc4b3e329'
down_revision = '557d591a3831'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
