"""empty message

Revision ID: 496d7c563698
Revises: d5add345c871
Create Date: 2022-09-26 06:44:24.916938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '496d7c563698'
down_revision = 'd5add345c871'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('popular', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'popular', ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'popular', type_='unique')
    op.drop_column('popular', 'user_id')
    # ### end Alembic commands ###
