"""empty message

Revision ID: 557d591a3831
Revises: 5fd1f8c48c6c
Create Date: 2022-09-26 20:51:48.242975

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '557d591a3831'
down_revision = '5fd1f8c48c6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('modified_at', sa.DateTime(), nullable=True))
    op.drop_column('game', 'created_at')
    op.add_column('popular', sa.Column('modified_at', sa.DateTime(), nullable=True))
    op.drop_column('popular', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('popular', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('popular', 'modified_at')
    op.add_column('game', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('game', 'modified_at')
    # ### end Alembic commands ###
