"""empty message

Revision ID: 62ccd4610de8
Revises: 
Create Date: 2022-09-26 04:31:37.338570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62ccd4610de8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'popular', ['user'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'popular', type_='unique')
    # ### end Alembic commands ###
