"""empty message

Revision ID: d5add345c871
Revises: 62ccd4610de8
Create Date: 2022-09-26 06:17:25.327976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5add345c871'
down_revision = '62ccd4610de8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('popular_user_key', 'popular', type_='unique')
    op.drop_column('popular', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('popular', sa.Column('user', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('popular_user_key', 'popular', ['user'])
    # ### end Alembic commands ###
